services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-care-plus-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-pet-care-plus}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-user}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      SPRING_DATA_REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - pet-care-plus-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.11-bullseye
    container_name: pet-care-plus-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pet-care-plus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./var/logs/postgresql:/var/log/postgresql
    networks:
      - pet-care-plus-network

  redis:
    image: redis:7.0.12-alpine
    container_name: pet-care-plus-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD:-password}"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - pet-care-plus-network

volumes:
  postgres-data:
  redis-data:

networks:
  pet-care-plus-network:
    driver: bridge
